const ATypes = {
  SET_TOPICS: "SET_TOPICS",
  SET_USER: "SET_USER",
  SET_ANSWERS: "SET_ANSWERS",
  SET_GAMES: "SET_GAMES",
  UPDATE_RANDOM_QUESTIONS: "UPDATE_RANDOM_QUESTIONS",
};

export default ATypes;
